runtime: python37

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /static
  static_dir: static
  http_headers:
    Access-Control-Allow-Origin: https://mail-reader-42.appspot.com/


- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
